import type { Hero } from './Hero';
import type { WinConditionAnalysis } from './WinConditionAnalyzer';
import { winConditionToString } from './SuggestionTypes';
import { ALL_MAPS, findHeroByName } from './HeroData';

/**
 * Generate a formatted text summary of a completed draft.
 */
export function exportDraftAsText(
  map: string,
  team1Picks: Hero[],
  team2Picks: Hero[],
  team1Bans: Hero[],
  team2Bans: Hero[],
  analysis1?: WinConditionAnalysis,
  analysis2?: WinConditionAnalysis
): string {
  const divider = '═══════════════════════════════════';
  const lines: string[] = [];

  lines.push(divider);
  lines.push('  HotsDrafter - Draft Summary');
  lines.push(`  Map: ${map}`);
  lines.push(divider);
  lines.push('');

  // Bans
  lines.push('BANS');
  lines.push(`Team 1: ${team1Bans.map(h => h.nicknames[0]).join(', ') || 'None'}`);
  lines.push(`Team 2: ${team2Bans.map(h => h.nicknames[0]).join(', ') || 'None'}`);
  lines.push('');

  // Team 1 Picks
  lines.push('TEAM 1 PICKS');
  team1Picks.forEach((h, i) => {
    lines.push(`${i + 1}. ${h.nicknames[0]} (${h.role})`);
  });
  if (analysis1) {
    lines.push(`Win Condition: ${winConditionToString(analysis1.primary)}`);
  }
  lines.push('');

  // Team 2 Picks
  lines.push('TEAM 2 PICKS');
  team2Picks.forEach((h, i) => {
    lines.push(`${i + 1}. ${h.nicknames[0]} (${h.role})`);
  });
  if (analysis2) {
    lines.push(`Win Condition: ${winConditionToString(analysis2.primary)}`);
  }
  lines.push('');

  lines.push('Generated by HotsDrafter Web');
  return lines.join('\n');
}

/**
 * Encode a draft into shareable URL params.
 */
export function encodeDraftUrl(
  mapIdx: number,
  team1Picks: Hero[],
  team2Picks: Hero[],
  team1Bans: Hero[],
  team2Bans: Hero[]
): string {
  const params = new URLSearchParams();
  params.set('map', String(mapIdx));
  params.set('t1p', team1Picks.map(h => h.nicknames[0]).join(','));
  params.set('t2p', team2Picks.map(h => h.nicknames[0]).join(','));
  params.set('t1b', team1Bans.map(h => h.nicknames[0]).join(','));
  params.set('t2b', team2Bans.map(h => h.nicknames[0]).join(','));
  return `/draft/result?${params.toString()}`;
}

/**
 * Decode hero nicknames from URL params back to Hero objects.
 * Returns undefined for heroes that can't be found.
 */
export function decodeHeroList(param: string | null): Hero[] {
  if (!param) return [];
  return param
    .split(',')
    .filter(Boolean)
    .map(name => findHeroByName(decodeURIComponent(name)))
    .filter((h): h is Hero => h !== undefined);
}

/**
 * Decode the map index from URL params.
 * Returns 0 (first map) if invalid.
 */
export function decodeMapIndex(param: string | null): number {
  if (!param) return 0;
  const idx = parseInt(param, 10);
  if (isNaN(idx) || idx < 0 || idx >= ALL_MAPS.length) return 0;
  return idx;
}
